#!/usr/bin/env bash
# generate-build-info.sh — Write build metadata into _build_info.py
#
# Reads the server version from __version__.py and the rules provenance
# from aidlc-rules/.sync-metadata, then writes them into a Python module
# that the server can import at runtime.
#
# Called automatically by CI before building the package.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# Server version from __version__.py
SERVER_VERSION=$(python3 -c "
import re, pathlib
text = pathlib.Path('$PROJECT_ROOT/aidlc_mcp_server/__version__.py').read_text()
print(re.search(r'__version__\s*=\s*\"(.+?)\"', text).group(1))
")

# Rules provenance from .sync-metadata
SYNC_META="$PROJECT_ROOT/aidlc-rules/.sync-metadata"
if [ -f "$SYNC_META" ]; then
    RULES_COMMIT=$(grep '^monorepo_commit=' "$SYNC_META" | cut -d= -f2 || echo "unknown")
    RULES_SOURCE=$(grep '^source=' "$SYNC_META" | cut -d= -f2 || echo "unknown")
    # Fallback for legacy format
    if [ -z "$RULES_COMMIT" ] || [ "$RULES_COMMIT" = "" ]; then
        RULES_COMMIT=$(grep '^commit=' "$SYNC_META" | cut -d= -f2 || echo "unknown")
    fi
    if [ -z "$RULES_SOURCE" ] || [ "$RULES_SOURCE" = "" ]; then
        RULES_SOURCE="monorepo-local"
    fi
else
    RULES_COMMIT="unknown"
    RULES_SOURCE="unknown"
fi

BUILD_TS=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

cat > "$PROJECT_ROOT/aidlc_mcp_server/_build_info.py" <<EOF
"""Build-time metadata — regenerated by CI or scripts/generate-build-info.sh."""

server_version = "$SERVER_VERSION"
rules_source = "$RULES_SOURCE"
rules_commit = "$RULES_COMMIT"
build_timestamp = "$BUILD_TS"
EOF

echo "Generated _build_info.py:"
echo "  server_version=$SERVER_VERSION"
echo "  rules_source=$RULES_SOURCE"
echo "  rules_commit=$RULES_COMMIT"
echo "  build_timestamp=$BUILD_TS"
