#!/usr/bin/env bash
# sync-aidlc-rules.sh — Copy the aidlc-rules/ directory from the monorepo root
# into the local aidlc-rules/ directory and the bundled package directory.
#
# Since the aidlc-mcp-server now lives inside the aidlc-workflows monorepo,
# rules are sourced locally rather than cloned from a remote repository.
#
# Usage:
#   ./scripts/sync-aidlc-rules.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
MONOREPO_ROOT="$(cd "$PROJECT_ROOT/.." && pwd)"

SOURCE="$MONOREPO_ROOT/aidlc-rules"

if [ ! -d "$SOURCE" ]; then
    echo "Error: aidlc-rules/ not found at monorepo root ($SOURCE)." >&2
    echo "Expected directory structure:" >&2
    echo "  <monorepo-root>/aidlc-rules/        ← source of truth" >&2
    echo "  <monorepo-root>/aidlc-mcp-server/   ← this project" >&2
    exit 1
fi

if [ ! -d "$SOURCE/aws-aidlc-rules" ]; then
    echo "Error: $SOURCE/aws-aidlc-rules/ not found. Rules directory appears incomplete." >&2
    exit 1
fi

echo "Syncing aidlc-rules from monorepo root..."
echo "  source: $SOURCE"

# Capture the current monorepo commit for provenance
COMMIT_HASH="unknown"
if command -v git &>/dev/null && git -C "$MONOREPO_ROOT" rev-parse HEAD &>/dev/null; then
    COMMIT_HASH=$(git -C "$MONOREPO_ROOT" rev-parse HEAD)
fi

# Replace local rules with monorepo content
TARGET="$PROJECT_ROOT/aidlc-rules"
rm -rf "$TARGET"
cp -R "$SOURCE" "$TARGET"

# Write a provenance file so we know what version we synced
METADATA="# Auto-generated by scripts/sync-aidlc-rules.sh — do not edit
source=monorepo-local
monorepo_commit=$COMMIT_HASH
synced_at=$(date -u +"%Y-%m-%dT%H:%M:%SZ")"

echo "$METADATA" > "$TARGET/.sync-metadata"

# Also copy rules into the Python package so they're included in wheels
BUNDLED="$PROJECT_ROOT/aidlc_mcp_server/aidlc-rules"
rm -rf "$BUNDLED"
cp -R "$SOURCE" "$BUNDLED"
echo "$METADATA" > "$BUNDLED/.sync-metadata"

echo ""
echo "Done. Synced aidlc-rules/ from monorepo root."
echo "  commit: $COMMIT_HASH"
echo "  target: $TARGET"
echo "  bundled: $BUNDLED"
